# Generated by Django 4.1.5 on 2023-01-09 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('category_name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.OneToOneField(max_length=500, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FridgeApp.items')),
                ('category_date', models.DateField()),
            ],
        ),
    ]
